### ISSUE TITLE
이미지 삽입 에러

### ISSUE THREAD

**Issue by yujeong-claudia** [yujeong-claudia/eBook#1]
```
Failed to load resource: the server responded with a status of 404 ()
```
이미지가 들어가지않고 에러가 나는 현상
=> 단순한 **경로** 문제로
`href="/css/style.css"` 에서
`href="/static/css/style.css"`으로 수정하니까 해결됨

- [x] 이미지 삽입 에러

**Comment by yujeong-claudia** [comment]
회원가입 API 디버깅 중 또다시 `Failed to load resource: the server responded with a status of 404 ()` 에러 발생
전에는 경로설정 문제로 경로를 바꿔주니까 로고가 제대로 나왔다.
하지만 현재는 입력값 모두 제대로 들어간 상태이며, 로고 마저 제대로 출력되는데 404가 나오는 현상..
검색해보니까 개발에는 문제가 없다고 하는데

인터넷 웹 브라우저의 주소창에 표시되는 웹사이트를 대표하는 아이콘, 파피콘이 경로를 찾지 못해서 발생하는 현상이라고 한다.

select인 경우 `<link rel="shortcut icon" href="#">` 문구만 삽입하면 된다고 하나 Insert나 Update시 쿼리가 중복으로 실행되니 해결방법이 아니고, 회원가입 API는 insert라 나에게 맞는 방법이 아니다.

검색결과 `<head></head>` 바로 밑에 `<link rel="icon" href="data:;base64,iVBORw0KGgo=">` 문구를 추가해주면 된다고 하여
추가 후 문제가 해결됐다.

**Comment by yujeong-claudia** [comment]
**`413 (Payload Too Large)`**
- 파일 업로드시 파일명 암호화 및 한글 이름 이미지 가능하게 설정하는 과정에서 413 에러발생
처음에는 암호화와 한글 이미지 저장이 실패한 줄 알았으나 images 파일에 한글이름 파일이 암호화된 이름으로 잘 저장됐다.
- 콘솔창을 확인해보니 `request entity too large`  너무 큰 사이즈의 request를 보내서 제한이 걸린 것이다.

```
const bodyParser = require('body-parser'); app.use(bodyParser.json({limit: 5000000})); // 5MB app.use(bodyParser.urlencoded({limit: 5000000, extended: true, parameterLimit:50000})); // limit: 5MB
```
위에 코드를 넣어주면 된다고 하나 어디에 위치시켜야할지 모르겠다.
그래서 다시 검색했다.
<br>

- [x] Nginx 에서 받을 수 있는 body size를 늘려주는 작업이 필요하다.
- [x] 해당 값을 설정해주지 않을 경우 Default 값은 1MB
- [x] 따라서 상황에 맞게 해당 Ingress 의 Proxy-body-size 를 설정해줄 필요가 있다.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
		nginx.ingress.kubernetes.io/proxy-body-size: 20m
		nginx.ingress.kubernetes.io/client-body-buffer-size: 10m
```

yml 파일에 위와 같이 추가했더니 에러가 해결됐다.

** 추가로 알게 된 사실 **
- yml, yaml의 차이 => 같다.
- 옛날 Windows에서 Extensions는 파일확장자가 3자로 제한되는 특성 때문에 `.html` 대신 `.htm` 으로도 쓰였는데 이와 같은 원리이다.
